name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change to "master" if your branch is named "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AIRCALLDASHBOARD }}"
          channelId: live
          projectId: your-firebase-project-id  # Change this to your Firebase project ID
